src/Entity/Beer.php
<?php

namespace App\Entity;

use App\Repository\BeerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BeerRepository::class)
 */
class Beer
{

    const STATUS_AVAILABLE = "available";
    const STATUS_UNAVAILABLE = "unavailable";

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $published_at;

    /**
     * @ORM\ManyToOne(targetEntity=Country::class, inversedBy="beers")
     */
    private $country;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="beers")
     */
    private $categories;

    /**
     * @ORM\ManyToMany(targetEntity=Client::class, mappedBy="beers")
     */
    private $clients;

    /**
     * @ORM\Column(type="smallint", nullable=true, options={"unsigned" : true })
     */
    private $rating;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $status;

    /**
     * @ORM\Column(type="decimal", precision=3, scale=1, nullable=true)
     */
    private $degree;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2, nullable=true)
     */
    private $price;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->clients = new ArrayCollection();

        // mettre une valeur par défaut
        $this->status = self::STATUS_AVAILABLE ;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(?\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    /**
     * @return Collection|Client[]
     */
    public function getClients(): Collection
    {
        return $this->clients;
    }

    public function addClient(Client $client): self
    {
        if (!$this->clients->contains($client)) {
            $this->clients[] = $client;
            $client->addBeer($this);
        }

        return $this;
    }

    public function removeClient(Client $client): self
    {
        if ($this->clients->removeElement($client)) {
            $client->removeBeer($this);
        }

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        if(!in_array($status, [self::STATUS_AVAILABLE, self::STATUS_UNAVAILABLE])){
            throw new \InvalidArgumentException("Invalid status");
        }

        $this->status = $status;

        return $this;
    }

    public function getDegree(): ?string
    {
        return $this->degree;
    }

    public function setDegree(?string $degree): self
    {
        $this->degree = $degree;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): self
    {
        $this->price = $price;

        return $this;
    }

}

src/Controller/BarController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use App\Entity\Beer;

class BarController extends AbstractController
{
    private HttpClientInterface $_client;

    public function __construct(HttpClientInterface $client) {
        $this->_client = $client;
    }

    #[Route('/', name: 'home')]
    public function root(): Response
    {
        /** @var BeerRepository $repository */
        $repository = $this->getDoctrine()->getRepository(Beer::class);

        return $this->render('bar/index.html.twig', [
            'beers' => $repository->getThreeLastElement()
        ]);
    }

    #[Route('/bar', name: 'bar')]
    public function index(): Response
    {
        return $this->render('bar/bar.html.twig', [
            'controller_name' => 'BarController',
        ]);
    }

    #[Route('/contact', name: 'contact')]
    public function contact(): Response
    {
        return $this->render('bar/contact.html.twig', [
            'title' => 'My Contact Page',
        ]);
    }

    #[Route('/mention', name: 'mention')]
    public function mention(): Response{
        return $this->render('bar/mention.html.twig');
    }


    //récupération de l'id beer

    #[Route('/beer/{id}', name: 'showbeer')]
    public function show($id): Response{
        $repository = $this->getDoctrine()->getRepository(Beer::class);

        return $this->render('bar/showbeer.html.twig', [
            'beer' => $repository->find($id)
        ]);
    }

    
    #[Route('/beers', name: 'beers')]
    public function beers(): Response{
        $repository = $this->getDoctrine()->getRepository(Beer::class);

        return $this->render('bar/beers.html.twig', [
            'beers' => $repository->findAll()
        ]);
    }

    #[Route('/newbeer', name:'create_beer')]
    public function createBeer(){
        $entityManager = $this->getDoctrine()->getManager();

        $beer = new Beer();
        $beer->setname('Super Beer');
        $beer->setPublishedAt(new \DateTime());
        $beer->setDescription('Ergonomic and stylish!');
        $beer->setRating(rand(0, 10));
        $beer->setStatus(rand(0, 1) ? 'available' : 'unavailable');

        $degrees = [0, 5, 4.5, 8, 9.5];
        $rand_keys = array_rand($degrees, 1);

        $beer->setDegree($degrees[$rand_keys]);

        // tell Doctrine you want to (eventually) save the Product (no queries yet)
        $entityManager->persist($beer);

        // actually executes the queries (i.e. the INSERT query)
        $entityManager->flush();

        return new Response('Saved new beer with id '.$beer->getId());
    }
}

templates/bar/bar.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page Bar{% endblock %}

{% block sidebar %}
    Sidebar
{% endblock %}

{% block body %}
    <div class="row">
        <h1>Bar</h1>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <h5 class="card-header">Featured</h5>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <h5 class="card-header">Featured</h5>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/bar/beers.html.twig
{% extends 'base.html.twig' %}

{% block title %}List of beer{% endblock %}

{% block sidebar %}
    Sidebar
{% endblock %}

{% block body %}
    <div class="row">
        <h1>The beers</h1>
    </div>

    <div class="row">
        {% for beer in beers %}
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Name : {{ beer.name }}</h2>
							<p class="card-text">Degree : {{ beer.degree }}</p>
							<p class="card-text">Date : {{ beer.publishedAt | date('d-m-y h:s:m') }}</p>
							<p class="card-text">Rating : {{ beer.rating }}</p>
							<p class="card-text">Price : {{ beer.price }} $</p>
							<img src="{{ asset('build/images/beer_00.jpeg') }}" />
							<p>{{ beer.description }}</p>
                            {% if beer.status == 'unavailable' %}
								<p class="text-danger">Status : {{ beer.status }}</p>
							{% else %}
								<p class="text-success">Status : {{ beer.status }}</p>
							{% endif %}

                            <a href="{{ path('showbeer', { 'id': beer.id }) }}" class="btn btn-primary stretched-link">Visualiser</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/bar/contact.html.twig
{% extends('base.html.twig') %}

{% block body %}
    <h1>{{ title }}</h1>
{% endblock %}

templates/bar/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home Page{% endblock %}

{% block body %}
    <div class="row">
        <h1>Open Bar</h1>
    </div>

    <div class="row">
        {% for beer in beers %}
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Name : {{ beer.name }}</h2>
							<p class="card-text">Degree : {{ beer.degree }}</p>
							<p class="card-text">Date : {{ beer.publishedAt | date('d-m-y h:s:m') }}</p>
							<p class="card-text">Rating : {{ beer.rating }}</p>
							<p class="card-text">Price : {{ beer.price }} $</p>
							<img src="{{ asset('build/images/beer_00.jpeg') }}" />
							<p>{{ beer.description }}</p>
                            {% if beer.country %}
								<p>Country : {{ beer.country.name }}</p>
								<p class="text-primary">Address : {{ beer.country.address }}</p>
							{% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/bar/mention.html.twig
{% extends 'base.html.twig' %}

{% block sidebar %}
    Sidebar
{% endblock %}

{% block body %}
    <div class="row">
        <h1>Mention</h1>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Quote
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/bar/showbeer.html.twig
{% extends 'base.html.twig' %}

{% block title %} Hello beer {% endblock %}

{% block body %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Name : {{ beer.name }}</h2>
                    <p class="card-text">Degree : {{ beer.degree }}</p>
                    <p class="card-text">Date : {{ beer.publishedAt | date('d-m-y h:s:m') }}</p>
                    <p class="card-text">Rating : {{ beer.rating }}</p>
                    <p class="card-text">Price : {{ beer.price }} $</p>
                    <img src="{{ asset('build/images/beer_00.jpeg') }}" />
                    <p>{{ beer.description }}</p>
                    {% if beer.status == 'unavailable' %}
                        <p class="text-danger">Status : {{ beer.status }}</p>
                    {% else %}
                        <p class="text-success">Status : {{ beer.status }}</p>
                    {% endif %}
                    <a href="{{ ('/') }}" class="btn btn-primary stretched-link">Retourner à la page d'accueil</a>
            </div>
        </div>
    </div>

</div>
{% endblock %}